### ISSUE TITLE
1회차 주제

### ISSUE THREAD

**Issue by ggyu0629** [IMS-STUDY/Docker-Study#1]
### 이론
- 도커란 무엇인가?
    - 도커의 정체는?
    - 데이터나 프로그램을 독립된 환경에 격리해야하는 이유
    - 프로그램의 격리란?
    
- 서버와 도커
    - 서버의 두 가지 의미
    - 컨테이너를 이용해 여러가지 서버 기능을 안전하게 함께 실행하기
    
- 도커의 동작 원리
    - 도커의 구조
    
- 도커 허브와 이미지, 컨테이너
    - 이미지와 컨테이너
    - 도커 허브와 도커 이미지  

- 도커 컨테이너의 생애주기와 데이터 저장
    - 도커 컨테이너는 '쓰고 버리는' 일회용품
    - 데이터 저장

- 도커의 장점과 단점
    - 도커의 구조와 성질 및 그 장단점
    - 도커의 장점과 단점
    - 도커의 주 용도

### 실습 (캡처 후 블로그 쓰기)
- 실습환경 구축하기
    - 도커 데스크톱의 첫 실행 및 화면 확인(캡쳐)
    - 도커 컨테이너를 다루는 명령어 알아보기
    - 도커 컨테이너를 프롬프트로 다룰 때 주의할 점
- 컨테이너로 Hello World 실행하기
- Apache 서버로 웹페이지 출력하기
- Ngnix 서버로 웹페이지 출력하기

## 마감기한
- 24.01.22 자정

**Comment by yyechan0602** [comment]
https://yyechan0602.github.io/docker/Docker/
https://yyechan0602.github.io/docker/Docker-Installation/

**Comment by bnh5992** [comment]
https://bnh4924.tistory.com/61
https://bnh4924.tistory.com/62

**Comment by abbiddo** [comment]
https://abbiddo.tistory.com/132
https://abbiddo.tistory.com/133
https://abbiddo.tistory.com/134
https://abbiddo.tistory.com/135
https://abbiddo.tistory.com/136
https://abbiddo.tistory.com/137
https://abbiddo.tistory.com/138

**Comment by ggyu0629** [comment]
https://qrazy-every-day.tistory.com/79
https://qrazy-every-day.tistory.com/79
https://qrazy-every-day.tistory.com/79

**Comment by JoEunSang** [comment]
https://codehouse0224.tistory.com/68
