### ISSUE TITLE
2회차 주제

### ISSUE THREAD

**Issue by ggyu0629** [IMS-STUDY/Docker-Study#3]
### 컨테이너의 기본적인 사용법
- 도커 명령어
- 기본적인 명령어 구조 정리
- version 명령어를 사용해보자

### 조작 관련 커맨드 정리
- 컨테이너 조작
- 이미지 조작
- 볼륨 조작
- 네트워크 조작
- 그 밖의 상위 커맨드
- 단독으로 쓰이는 커맨드

### 컨테이너의 생성과 삭제, 실행, 정지
- docker run 커맨드와 docker stop, docker rm 커맨드
- docker ps 커맨드
- 컨테이너를 생성하고, 실행, 상태확인, 종료, 삭제해보자

### 컨테이너의 통신
- 아파치란?
- 컨테이너와 통신하기 위한 방법
- 통신이 가능한 컨테이너 만들기

### 컨테이너 생성에 익숙해지기
- 다양한 유형의 컨테이너
- 아파치 컨테이너를 여러 개 실행하기
- Nginx 컨테이너 실행하기
- MySQL 컨테이너 실행하기

### 이미지 삭제
- docker image rm 커맨드
- docker image ls 커맨드
- 이미지 삭제 하는법

### 마감기한
- 24/01/24 17시

**Comment by yyechan0602** [comment]
https://yyechan0602.github.io/docker/Command/
https://yyechan0602.github.io/docker/Docker-Lifecycle/

**Comment by abbiddo** [comment]
https://abbiddo.tistory.com/139
https://abbiddo.tistory.com/140
https://abbiddo.tistory.com/141
https://abbiddo.tistory.com/142

**Comment by bnh5992** [comment]
https://bnh4924.tistory.com/63

**Comment by JoEunSang** [comment]
https://codehouse0224.tistory.com/72
https://codehouse0224.tistory.com/73

**Comment by ggyu0629** [comment]
https://qrazy-every-day.tistory.com/83
https://qrazy-every-day.tistory.com/84
https://qrazy-every-day.tistory.com/85
