### ISSUE TITLE
3회차

### ISSUE THREAD

**Issue by ggyu0629** [IMS-STUDY/Docker-Study#5]
### 애플리케이션 빌드 실전 예제 - 자바
- Maven을 사용해 자바 애플리케이션을 빌드하는 Dockerfile을 만들자. 

### 멀티 스테이지 Dockerfile 스크립트 이해하기
- 멀티 스테이지 Dockerfile 스크립트의 동작 원리 공부하기
- 컨테이너 안에서 애플리케이션을 빌드하는 것이 왜 유용한지

### 레지스트리에 이미지 공유하기
- 레지스트리, 리포지타리, 이미지 태그 다루기
- 도커 허브에 직접 빌드한 이미지 push하기
- 로컬 네트워크에 전용 레지스트리가 있으면 편리한 점은 무엇인가?
- 이미지 태그를 효율적으로 사용하기

### 실용 도커 기술
- 컨테이너와 호스트 사이에 파일 복사
- 볼륨 마운트

**Comment by JoEunSang** [comment]
https://codehouse0224.tistory.com/75
https://codehouse0224.tistory.com/76

**Comment by yyechan0602** [comment]
https://yyechan0602.github.io/docker/DockerFile/
https://yyechan0602.github.io/docker/Multi-Stage-Build/
https://yyechan0602.github.io/docker/Sharing-Docker-Image/

**Comment by abbiddo** [comment]
https://abbiddo.tistory.com/143
https://abbiddo.tistory.com/144
https://abbiddo.tistory.com/145
https://abbiddo.tistory.com/146

**Comment by bnh5992** [comment]
https://bnh4924.tistory.com/65
