### ISSUE TITLE
4회차

### ISSUE THREAD

**Issue by ggyu0629** [IMS-STUDY/Docker-Study#7]
### gradle 기반의 Spring 웹 서버를 Dockerfile로 만들자.
- 멀티 스테이지를 이용해보자.
- postman, 웹 클라이언트 등등 통신을 진행해보자.
- application.yml 파일을 Dockerfile로 불러올 때 저장되는 이름(버전관리 등) 여러가지 시도해서 Dockerfile을 생성해보자.

### 추가
- GameServer 스터디에서 진행한 채팅서버, 클라이언트도 진행해보자.

### 마운트 추가내용
- 스토리지 마운트의 종류
- 스토리지 영역을 마운트하는 커맨드
- 바인드 마운트 해보기

### 도커 컴포즈
- 도커 컴포즈란?
- 도커 컴포즈 설치와 사용법을 학습하자

## 마감
24.02.01 17시

**Comment by abbiddo** [comment]
https://abbiddo.tistory.com/147
https://abbiddo.tistory.com/148
https://abbiddo.tistory.com/149

**Comment by bnh5992** [comment]
https://bnh4924.tistory.com/66
https://bnh4924.tistory.com/67

**Comment by yyechan0602** [comment]
https://yyechan0602.github.io/docker/Spring-To-Docker-Image/
https://yyechan0602.github.io/docker/Volume-Mount/
https://yyechan0602.github.io/docker/Docker-Compose/
